{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lei-get.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lei-get.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY_BASE: {{ .Values.secrets.secretKeyBase | quote }}
  LEI_GH_TOKEN: {{ .Values.secrets.ghToken | quote }}
{{- end }}
