name: default_elixir_ci

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop  # run CI on develop pushes

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: lowendinsight_get_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        otp: ['26.2']
        elixir: ['1.15.7']

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: zhulik/redis-action@1.1.0
        with:
          redis version: '7'
          number of databases: 20
      - name: Install Dependencies
        run: |
          npm install -g newman
          newman --version
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Setup Database
        run: MIX_ENV=test mix ecto.create && MIX_ENV=test mix ecto.migrate
      - name: Run Tests
        run: MIX_ENV=test mix coveralls.github
      - name: docker compose build and run
        run: docker compose up -d --build
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Postman tests
        run: newman run test/docker-compose.postman_collection.json --timeout-request 30000
